/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;
import Backend.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
public class frmFilm extends javax.swing.JFrame {

    /**
     * Creates new form frmFilm
     */
    public frmFilm() {
        initComponents();
        kosongkanForm();
        tampilkanData();
        tampilkanCmbRating();
    }
    
    public void kosongkanForm(){
    txtIdFilm.setText("");
    cmbRating.setSelectedIndex(0);
    txtJudul.setText("");
    txtGenre.setText("");
    txtSutradara.setText("");
    txtDurasi.setText("");
    cmbJadwalTayang.setSelectedIndex(0);
    txtKeterangan.setText("");
    }
     public  void tampilkanData(){
    String []kolom = {"ID", "Rating","Judul","Genre","Sutradara","Durasi","Keterangan"};
    ArrayList<Film>list = new Film().getAll();
    Object rowData[] = new Object[7];
    
    tblFilm.setModel(new DefaultTableModel(new Object[][]{}, kolom));
    for (int i = 0; i<list.size(); i++){
        rowData[0]= list.get(i).getIdFilm();
        rowData[1]= list.get(i).getRating().getRatingFilm();
        rowData[2]= list.get(i).getJudul();
        rowData[3]= list.get(i).getGenre();
        rowData[4]= list.get(i).getSutradara();
        rowData[5]= list.get(i).getDurasi();
        rowData[6]= list.get(i).getKeterangan();
        ((DefaultTableModel)tblFilm.getModel()).addRow(rowData);
    }
    }
     public void cari (String keyword){
     String []kolom = {"ID", "Rating","Judul","Genre","Sutradara","Durasi","Keterangan"};
    ArrayList<Film>list = new Film().search(keyword);
    Object rowData[] = new Object[7];
    
    tblFilm.setModel(new DefaultTableModel(new Object[][]{}, kolom));
    for (int i = 0; i<list.size(); i++){
        rowData[0]= list.get(i).getIdFilm();
        rowData[1]= list.get(i).getRating().getRatingFilm();
        rowData[2]= list.get(i).getJudul();
        rowData[3]= list.get(i).getGenre();
        rowData[4]= list.get(i).getSutradara();
        rowData[5]= list.get(i).getDurasi();
        rowData[6]= list.get(i).getKeterangan();
        ((DefaultTableModel)tblFilm.getModel()).addRow(rowData);
    }
     }
     
     public void tampilkanCmbRating(){
     cmbRating.setModel(new DefaultComboBoxModel(new Rating().getAll().toArray()));
     }
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdFilm = new javax.swing.JTextField();
        cmbRating = new javax.swing.JComboBox<>();
        txtJudul = new javax.swing.JTextField();
        txtGenre = new javax.swing.JTextField();
        txtSutradara = new javax.swing.JTextField();
        txtDurasi = new javax.swing.JTextField();
        cmbJadwalTayang = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnTambahBaru = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFilm = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtKeterangan = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID FILM");

        jLabel2.setText("RATING");

        jLabel3.setText("JUDUL");

        jLabel4.setText("GENRE");

        jLabel5.setText("SUTRADARA");

        jLabel6.setText("DURASI");

        jLabel7.setText("JADWAL TAYANG");

        txtIdFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdFilmActionPerformed(evt);
            }
        });

        cmbRating.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRatingActionPerformed(evt);
            }
        });

        txtJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJudulActionPerformed(evt);
            }
        });

        cmbJadwalTayang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "13.00 WIB", "14.00 WIB", "14.35 WIB", "15.00 WIB", "15.55 WIB", "16.15 WIB", "16.30 WIB", "17.25 WIB", "18.00 WIB" }));
        cmbJadwalTayang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbJadwalTayangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbJadwalTayangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbJadwalTayangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmbJadwalTayangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmbJadwalTayangMouseReleased(evt);
            }
        });
        cmbJadwalTayang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJadwalTayangActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnTambahBaru.setText("Tambah Baru");
        btnTambahBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahBaruActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("OCR-A BT", 1, 48)); // NOI18N
        jLabel8.setText("FILM");

        tblFilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFilm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFilmMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFilm);

        txtKeterangan.setColumns(20);
        txtKeterangan.setRows(5);
        jScrollPane3.setViewportView(txtKeterangan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(487, 487, 487)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTambahBaru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCari)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCari)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1351, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdFilm, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtGenre, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtJudul)
                                        .addComponent(cmbRating, javax.swing.GroupLayout.Alignment.LEADING, 0, 359, Short.MAX_VALUE)
                                        .addComponent(txtSutradara, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbJadwalTayang, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSutradara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmbJadwalTayang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambahBaru)
                            .addComponent(btnHapus)
                            .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCari))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahBaruActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
    }//GEN-LAST:event_btnTambahBaruActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        cari(txtCari.getText());
    }//GEN-LAST:event_btnCariActionPerformed

    private void txtIdFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdFilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdFilmActionPerformed

    private void txtJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJudulActionPerformed

    private void cmbJadwalTayangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJadwalTayangActionPerformed
        // TODO add your handling code here:
        Film flm = new Film();
        flm.jadwalTayang((String)cmbJadwalTayang.getSelectedItem());
        
    }//GEN-LAST:event_cmbJadwalTayangActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Film flm = new Film();
        flm.setIdFilm(Integer.parseInt(txtIdFilm.getText()));
        flm.setRating((Rating)cmbRating.getSelectedItem());
        flm.setJudul(txtJudul.getText());
        flm.setGenre(txtGenre.getText());
        flm.setSutradara(txtSutradara.getText());
        flm.setDurasi(txtDurasi.getText());
        flm.setKeterangan(flm.jadwalTayang((String) cmbJadwalTayang.getSelectedItem()));
        flm.save();
        txtIdFilm.setText(Integer.toString(flm.getIdFilm()));
        
        tampilkanData();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblFilm.getModel();
        int row = tblFilm.getSelectedRow();
        
        Film flm = new Film().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        flm.delete();
        kosongkanForm();
        tampilkanData();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblFilmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFilmMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblFilm.getModel();
        int row = tblFilm.getSelectedRow();
        Film flm = new Film().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        txtIdFilm.setText(String.valueOf(flm.getIdFilm()));
        cmbRating.getModel().setSelectedItem(flm.getRating());
        txtJudul.setText(flm.getJudul());
        txtGenre.setText(flm.getGenre());
        txtSutradara.setText(flm.getSutradara());
        txtDurasi.setText(flm.getDurasi());
        cmbJadwalTayang.getModel().setSelectedItem(flm.getKeterangan());
        txtKeterangan.setText(flm.getKeterangan());
    }//GEN-LAST:event_tblFilmMouseClicked

    private void cmbRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRatingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRatingActionPerformed

    private void cmbJadwalTayangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbJadwalTayangMouseClicked
        // TODO add your handling code here:
//        Film flm = new Film();
//        txtKeterangan.setText((flm.jadwalTayang((String) cmbJadwalTayang.getSelectedItem())));
    }//GEN-LAST:event_cmbJadwalTayangMouseClicked

    private void cmbJadwalTayangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbJadwalTayangMousePressed
        // TODO add your handling code here:
        Film flm = new Film();
        txtKeterangan.setText((flm.jadwalTayang((String) cmbJadwalTayang.getSelectedItem())));
    }//GEN-LAST:event_cmbJadwalTayangMousePressed

    private void cmbJadwalTayangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbJadwalTayangMouseEntered
        // TODO add your handling code here:
//        Film flm = new Film();
//        txtKeterangan.setText((flm.jadwalTayang((String) cmbJadwalTayang.getSelectedItem())));
    }//GEN-LAST:event_cmbJadwalTayangMouseEntered

    private void cmbJadwalTayangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbJadwalTayangMouseReleased
        // TODO add your handling code here:
//        Film flm = new Film();
//        txtKeterangan.setText((flm.jadwalTayang((String) cmbJadwalTayang.getSelectedItem())));
    }//GEN-LAST:event_cmbJadwalTayangMouseReleased

    private void cmbJadwalTayangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbJadwalTayangMouseExited
        // TODO add your handling code here:
//        Film flm = new Film();
//        txtKeterangan.setText((flm.jadwalTayang((String) cmbJadwalTayang.getSelectedItem())));
    }//GEN-LAST:event_cmbJadwalTayangMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFilm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTambahBaru;
    private javax.swing.JComboBox<String> cmbJadwalTayang;
    private javax.swing.JComboBox<String> cmbRating;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTable tblFilm;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtDurasi;
    private javax.swing.JTextField txtGenre;
    private javax.swing.JTextField txtIdFilm;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextArea txtKeterangan;
    private javax.swing.JTextField txtSutradara;
    // End of variables declaration//GEN-END:variables
}
